version: "3.8"

services:
  mysql:
    build:
      context: .
      dockerfile: db.dockerfile
    container_name: mysql_folio_db
    ports:
      - "3306:3306"
    volumes:
      - schema:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_folio_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

volumes:
  schema: